### ISSUE TITLE
Wrong spelling for Password property in MailKitOptions

### ISSUE THREAD

**Issue by TheShihan** [myloveCc/NETCore.MailKit#3]
The property for "Password" is spelled wrong in file MailKitOptions.cs on line 42. It is written as "Passord", the "w" is missing.

**Comment by softlion** [comment]
Could this be fixed fast on the main nuget ?

**Comment by myloveCc** [comment]
Thanks, I have fixed the fault. I will push to nuget at next Monday. @TheShihan @softlion

**Comment by myloveCc** [comment]
I have just push a new version(1.1.1) to nuget. @softlion

**Comment by softlion** [comment]
Thks ! Btw i needed ImapClient instead, and this lib does not provide it so i removed it :(
