### ISSUE TITLE
Must issue a STARTTLS command first when using TLS-required services

### ISSUE THREAD

**Issue by cyborat** [myloveCc/NETCore.MailKit#6]
Enjoy using this extension, however when the server requires a TLS enabled connection, it looks like a STARTTLS command is needed prior to sending:

**Comment by cyborat** [comment]
SmtpCommandException: Must issue a STARTTLS command first
MailKit.Net.Smtp.SmtpClient.Authenticate(Encoding encoding, ICredentials credentials, CancellationToken cancellationToken)
MailKit.MailService.Authenticate(string userName, string password, CancellationToken cancellationToken)
NETCore.MailKit.MailKitProvider.InitSmtpClient()
System.Lazy.CreateValue()
System.Lazy.LazyInitValue()
NETCore.MailKit.Core.EmailService.SendEmail(string mailTo, string mailCc, string mailBcc, string subject, string message, Encoding encoding, bool isHtml)
NETCore.MailKit.Core.EmailService+<>c__DisplayClass6_0.<SendAsync>b__0()
System.Threading.Tasks.Task.Execute()
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
System.Runtime.CompilerServices.TaskAwaiter.GetResult()
SMGConnectSurveyIdentityService.Controllers.AccountController+<ForgotPassword>d__17.MoveNext() in AccountController.cs
-
				var code = await _userManager.GeneratePasswordResetTokenAsync(user);
				var callbackUrl = Url.Action(nameof(ResetPassword), "Account", new { userId = user.Id, code = code }, protocol: HttpContext.Request.Scheme);
				**await _emailService.SendAsync(model.Email, "Reset Password",**
				   $"Please reset your password by clicking here: <a href='{callbackUrl}'>link</a>");

**Comment by cyborat** [comment]
SmtpCommandException: Must issue a STARTTLS command first
MailKit.Net.Smtp.SmtpClient.Authenticate(Encoding encoding, ICredentials credentials, CancellationToken cancellationToken)
MailKit.MailService.Authenticate(string userName, string password, CancellationToken cancellationToken)
NETCore.MailKit.MailKitProvider.InitSmtpClient()
System.Lazy.CreateValue()
System.Lazy.LazyInitValue()
NETCore.MailKit.Core.EmailService.SendEmail(string mailTo, string mailCc, string mailBcc, string subject, string message, Encoding encoding, bool isHtml)
NETCore.MailKit.Core.EmailService+<>c__DisplayClass6_0.<SendAsync>b__0()
System.Threading.Tasks.Task.Execute()
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
System.Runtime.CompilerServices.TaskAwaiter.GetResult()
SMGConnectSurveyIdentityService.Controllers.AccountController+<ForgotPassword>d__17.MoveNext() in AccountController.cs

    var code = await _userManager.GeneratePasswordResetTokenAsync(user);
    var callbackUrl = Url.Action(nameof(ResetPassword), "Account", new { userId = user.Id, code = code }, protocol: HttpContext.Request.Scheme);
    await _emailService.SendAsync(model.Email, "Reset Password",
    $"Please reset your password by clicking here: <a href='{callbackUrl}'>link</a>");

**Comment by myloveCc** [comment]
I haven't tested the TLS connection, but I'll fix it. Thank you for your issue.

**Comment by myloveCc** [comment]
Set MailKitOptions property 'Security=true' to enable ssl or tls connetion.
