### ISSUE TITLE
netstandard2.0 not supported

### ISSUE THREAD

**Issue by hanweijun** [myloveCc/NETCore.MailKit#8]
Thanks for your project. I use it in my personal project. One issue is my class library targets netstandard2.0, so cannot refer MailKit2.0 directly because it targets netcoreapp2.0, So I have to download the source code and include it in mu solution and change the target to netcoreapp2.0 to compile.

As Microsoft suggests, a Net Core portable class library should target netstandard rather than netcoreapp. Is it all right to change the target to netstandard2.0?

**Comment by myloveCc** [comment]
You are right, i change the target to  netstandard2.0  at version 2.0.1
