### ISSUE TITLE
no authentication error

### ISSUE THREAD

**Issue by dragouf** [myloveCc/NETCore.MailKit#9]
Authentication should be optional. 
When I don't add any username and password it return a null exception error.

**Comment by mr-robert** [comment]
+1 and it's a very easy fix. Inside MailKitProvider.cs change the client.Authenticate lines to something like this:
`if (!string.IsNullOrEmpty(Options.Account))
            {
                client.Authenticate(Options.Account, Options.Password);
            }`

I created a custom implementation of MailKitProvider very similar to the one in source, with these changes, manually registered to the IoC container and it's working fine.

**Comment by myloveCc** [comment]
I have fix this issues ,thanks !
